version: 0.2

phases:
  install:
    commands:
      - echo "Installing Trivy"
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.25.2/trivy_0.25.2_Linux-64bit.tar.gz
      - tar zxvf trivy_0.25.2_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/
      - trivy --version
  build:
    commands:
      - echo "Listing files in the directory"
      - ls -l
      - echo "Parsing kubectl-deploy.yaml to list images"
      - |
        IMAGES=$(grep "image:" kubectl-deploy.yaml | awk '{print $2}' | sort | uniq)
        echo "Found images: $IMAGES"
        REPORT_FILE="all_scan_reports.txt"
        TEMP_FILE="temp_scan_report.txt"
        echo "Starting scan reports" > "$REPORT_FILE"  
        echo "Scanned report:" > "$TEMP_FILE"

        for IMAGE in $IMAGES; do
          echo "Scanning $IMAGE"
          echo "Scanning $IMAGE" >> "$REPORT_FILE"  
          trivy image --severity HIGH,CRITICAL $IMAGE >> "$REPORT_FILE" 2>&1
          echo "#############################################################" >> "$REPORT_FILE"
          
          
          TOTAL=$(grep -oP 'Total: \K\d+' "$REPORT_FILE" | tail -n 1)
          HIGH=$(grep -oP 'HIGH: \K\d+' "$REPORT_FILE" | tail -n 1)
          CRITICAL=$(grep -oP 'CRITICAL: \K\d+' "$REPORT_FILE" | tail -n 1)
          
          echo "$IMAGE:" >> "$TEMP_FILE"
          echo "No. of Vulnerabilities: Total($TOTAL), High($HIGH), Critical($CRITICAL)" >> "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"  
        done

        cat "$TEMP_FILE"

        cat "$TEMP_FILE" "$REPORT_FILE" > "${REPORT_FILE}.tmp"
        mv "${REPORT_FILE}.tmp" "$REPORT_FILE"
        rm "$TEMP_FILE"

artifacts:
  files:
    - kubectl-deploy.yaml
    - all_scan_reports.txt
