version: 0.2

phases:
  install:
    commands:
      - echo "Installing Trivy using binary"
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.25.2/trivy_0.25.2_Linux-64bit.tar.gz
      - tar zxvf trivy_0.25.2_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/

  build:
    commands:
      - echo "Parsing kubectl-deploy.yaml to list images"
      - |
        IMAGES=$(grep "image:" kubectl-deploy.yaml | awk '{print $2}')
        for IMAGE in $IMAGES; do
          echo "Scanning $IMAGE"
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE
        done

artifacts:
  files:
    - kubectl-deploy.yaml
