version: 0.2

phases:
  install:
    commands:
      - echo "Installing Trivy"
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.25.2/trivy_0.25.2_Linux-64bit.tar.gz
      - tar zxvf trivy_0.25.2_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/
      - trivy --version
  build:
    commands:
      - echo "Listing files in the directory"
      - ls -l
      - echo "Parsing kubectl-deploy.yaml to list images"
      - |
        IMAGES=$(grep "image:" kubectl-deploy.yaml | awk '{print $2}')
        echo "Found images: $IMAGES"
        REPORT_FILE="all_scan_reports.txt"
        echo "Starting scan reports" > "$REPORT_FILE"  

        for IMAGE in $IMAGES; do
          echo "Scanning $IMAGE"
          echo "Scanning $IMAGE" >> "$REPORT_FILE"  
          trivy image --severity HIGH,CRITICAL $IMAGE >> "$REPORT_FILE" 2>&1
          echo "#############################################################" >> "$REPORT_FILE"
        done

artifacts:
  files:
    - kubectl-deploy.yaml
    - all_scan_reports.txt
