version: 0.2

phases:
  install:
    commands:
      - echo "Installing Trivy"
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.25.2/trivy_0.25.2_Linux-64bit.tar.gz
      - tar zxvf trivy_0.25.2_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/
      - trivy --version

  build:
    commands:
      - echo "Listing files in the directory"
      - ls -l
      - echo "Parsing kubectl-deploy.yaml to list images"
      - |
        IMAGES=$(grep "image:" kubectl-deploy.yaml | awk '{print $2}')
        echo "Found images: $IMAGES"
        for IMAGE in $IMAGES; do
          echo "Scanning $IMAGE"
          REPORT_FILE="${IMAGE//:/_}_scan_report.txt"
          trivy image --severity HIGH,CRITICAL $IMAGE > "$REPORT_FILE" 2>&1
          if [ $? -ne 0 ]; then
            echo "Trivy scan failed for $IMAGE. Check the report for details."
          fi
          echo "Scan results for $IMAGE:"
          if [ -f "$REPORT_FILE" ]; then
            cat "$REPORT_FILE"
          else
            echo "Scan report file $REPORT_FILE not found."
          fi
        done

artifacts:
  files:
    - kubectl-deploy.yaml
    - "*_scan_report.txt"
